### ISSUE TITLE
Keywords can be assigned as variables

### ISSUE THREAD

**Issue by kostas-vl** [Kani-Maki-Gang/bld#110]
Built in keywords such as `bld_root_dir`, `bld_run_id` and `bld_start_time` can be used in the sections such as variables
```yaml
variables:
  bld_root_dir: some value
  bld_run_id: some other value
```
