### ISSUE TITLE
Support for actions

### ISSUE THREAD

**Issue by kostas-vl** [Kani-Maki-Gang/bld#251]
Bld should have support for action that will be a new yaml file that list a number of steps to be executed. The feature will be similar to github actions.

To go into further detail an action file could be structured as shown below
```yaml
name: An example action
type: action
version: 3

inputs:
    name: My name
    surname: My surname
    age: 100

steps: 
    - echo 'Hello world'
    
    - name: Echo something
      run: echo 'Hello again'
    
    - name: Print something using an input
      run: echo 'My name is ${{ inputs.name }} ${{ inputs.surname }} and I'm ${{ inputs.age }} years old'
    
    - name: Print something using an environment variable
      run: echo 'I'm a user of the ${{ env.search_engine }} search engine'

    - name: Call another pipeline
      uses: some-dir/example-pipeline.yaml
      with:
          name: ${{ inputs.name }}
          search_engine: ${{ env.search_engine }}

    - name: Call another action
      uses: actions-directory/another-action.yaml
      with:
          age: ${{ env.age }}
```

Based on the above example the action syntax will require:
1. Support for inputs
3. Support for the steps keyword in order to synchronously execute a number of steps
4. Each step can be either a shell command, an action call or a pipeline call
5. Steps that execute shell commands can be groups under a single name
