### ISSUE TITLE
Pipeline and action steps should support outputs

### ISSUE THREAD

**Issue by kostas-vl** [Kani-Maki-Gang/bld#255]
In the new version of the pipeline syntax both pipelines and action should have support for outputs on each step. To provide an example for this functionality; similar to GitHub actions; the outputs would be an environment variable where each output is a `key=value` syntax separated by the new line character. 

``` yaml
name: An example pipeline
type: pipeline
version: 3

jobs:
    main:
        - id: echo_command
          sh: echo "some_value=1000 >> $BLD_OUTPUT"

        - sh: echo ${{ steps.echo_command.outputs.some_value }}
```
