### ISSUE TITLE
Conditional execution of a step

### ISSUE THREAD

**Issue by kostas-vl** [Kani-Maki-Gang/bld#257]
Both pipelines and actions in the new version should support that use of the `if` key in order to conditionally execute a step. Below is an example usage.
``` yaml
jobs:
  main:
    - id: first_step
      sh: echo "some_value=1000 >> $BLD_OUTPUTS"

    - if: steps.first_step.outputs.some_value == 2000
      sh: echo 'The value is 2000'

    - if: steps.fist_step.outputs.some_value == 1000
      sh: echo 'The value is 1000'
```
