### ISSUE TITLE
OIDC authentication

### ISSUE THREAD

**Issue by kostas-vl** [Kani-Maki-Gang/bld#98]
Bld should use OIDC with the authentication process to open a browser directly and retrieve the tokens .

Additionally on a bld server the configuration should change as below
```yaml
local:
    server:
        auth:
            method: oidc
            issuer_url: https://someurl
            redirect_url: https://someredirecturl
            client_id: some_client_id
            client_secret: some_client_secret
            scopes: ["scope1", "scope2"]
            user_property: name
```
The user extractor should use the userinfo endpoint to retrieve either the name of the email of the user based on the `user_property` provided.
